20140101
[0, 1, 2]
[3, 4, 5, 6, 7, 8]
/scratch/SDF25/Hephaestus_Minicubes_v0_webdataset/1
/scratch/SDF25/Hephaestus_Minicubes_v0_webdataset/1/train_pos/sample-train_pos-000003.tar
000003
/scratch/SDF25/Hephaestus_Minicubes_v0_webdataset/1/train_pos/sample-train_pos-{000000..000003}.tar
Cuda available = False
Random seed set as 42
Traceback (most recent call last):
  File "/share/home/conradb/git/hephaestus-minicubes-ssl/mae_training/mae_linprobe.py", line 158, in <module>
    linprobe('../configs/linprobe_config.toml', True)
  File "/share/home/conradb/git/hephaestus-minicubes-ssl/mae_training/mae_linprobe.py", line 94, in linprobe
    checkpoint = torch.load(configs.model.checkpoint_path, map_location='cpu')
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/conradb/.conda/envs/torch2/lib/python3.11/site-packages/torch/serialization.py", line 1479, in load
    with _open_file_like(f, "rb") as opened_file:
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/conradb/.conda/envs/torch2/lib/python3.11/site-packages/torch/serialization.py", line 759, in _open_file_like
    return _open_file(name_or_buffer, mode)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/conradb/.conda/envs/torch2/lib/python3.11/site-packages/torch/serialization.py", line 740, in __init__
    super().__init__(open(name, mode))
                     ^^^^^^^^^^^^^^^^
IsADirectoryError: [Errno 21] Is a directory: 'checkpoints/mae/linprobe/vit_base_patch16/nblf61zs'
Traceback (most recent call last):
  File "/share/home/conradb/git/hephaestus-minicubes-ssl/mae_training/mae_linprobe.py", line 158, in <module>
    linprobe('../configs/linprobe_config.toml', True)
  File "/share/home/conradb/git/hephaestus-minicubes-ssl/mae_training/mae_linprobe.py", line 94, in linprobe
    checkpoint = torch.load(configs.model.checkpoint_path, map_location='cpu')
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/conradb/.conda/envs/torch2/lib/python3.11/site-packages/torch/serialization.py", line 1479, in load
    with _open_file_like(f, "rb") as opened_file:
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/conradb/.conda/envs/torch2/lib/python3.11/site-packages/torch/serialization.py", line 759, in _open_file_like
    return _open_file(name_or_buffer, mode)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/conradb/.conda/envs/torch2/lib/python3.11/site-packages/torch/serialization.py", line 740, in __init__
    super().__init__(open(name, mode))
                     ^^^^^^^^^^^^^^^^
IsADirectoryError: [Errno 21] Is a directory: 'checkpoints/mae/linprobe/vit_base_patch16/nblf61zs'
